=== fingo/xactus/original_repo_content/xml/tests/org.eclipse.wst.xml.validation.tests/testresources/samples/XMLExamples/PublicationCatalogue/Catalogue.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="http://www.eclipse.org/webtools/Catalogue" xmlns:c="http://www.eclipse.org/webtools/Catalogue">

	<complexType name="PublicationType">
		<sequence>
			<element name="title" type="string"></element>
			<element name="author" type="string" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="date" type="gYear"></element>
		</sequence>
	</complexType>
	
	<complexType name="BookType">
		<complexContent>
			<extension base="c:PublicationType">
			    <sequence>
                    <element name="isbn" type="string" />
					<element name="publisher" type="string"/>
                </sequence>
			</extension>
		</complexContent>
	</complexType>
	
	<complexType name="MagazineType">
		<complexContent>			
			<restriction base="c:PublicationType">
				<sequence>
                    <element name="title" type="string" />
					<element name="author" type="string" minOccurs="0" maxOccurs="0"/>
					<element name="date" type="gYear"></element>
				</sequence>
			</restriction>
		</complexContent>
	</complexType>
	
	<element name="Publication" type="c:PublicationType" abstract="true"></element>
	
	<element name="Book" type="c:BookType" substitutionGroup="c:Publication"></element>

	<element name="Magazine" type="c:MagazineType" substitutionGroup="c:Publication"></element>
	
	<element name="Catalogue">
		<complexType>
			<sequence>
				<element ref="c:Publication" maxOccurs="unbounded"></element>
			</sequence>
		</complexType>
	</element>
	
</schema>

=== fingo/xactus/original_repo_content/xml/tests/org.eclipse.wst.xml.validation.tests/testresources/samples/XMLExamples/PublicationCatalogue/Catalogue.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:Catalogue xmlns:c="http://www.eclipse.org/webtools/Catalogue" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.eclipse.org/webtools/Catalogue Catalogue.xsd ">
	<c:Book>
		<title>Professional XML Schema</title>
		<date>2001</date>
		<isbn>1-861005-47-4</isbn>
		<publisher>Wrox Press</publisher>
	</c:Book>
	<c:Magazine>
		<title>WebSphere Developer's Journal</title>
		<date>2001</date>
	</c:Magazine>
	<c:Book>
		<title>Java and XSLT</title>
		<date>2001</date>
		<isbn>0-596-00143-6</isbn>
		<publisher>O'Reilly</publisher>
	</c:Book>
</c:Catalogue>
