=== fingo/xactus/original_repo_content/xml/tests/org.eclipse.wst.xml.core.tests/src/org/eclipse/wst/xml/core/tests/format/testfiles/xml/xml-whitespace.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="song" type="xsdSong" />
	<!-- Define a simple type to test that the hierarchy overriding whitespace rule is observed -->
	<xsd:simpleType name="CollapsedString">
		<xsd:restriction base="xsd:string">
			<xsd:whiteSpace value="collapse" />
		</xsd:restriction>
	</xsd:simpleType>
	<!-- Define a simple type to test that the whitespace rule is inherited from the ancestor -->
	<xsd:simpleType name="Normalized">
  		<xsd:restriction base="xsd:normalizedString"></xsd:restriction>
  	</xsd:simpleType>
	<xsd:complexType name="xsdSong">
		<xsd:sequence>
			<!-- Whitespace should be replaced -->
			<xsd:element name="artist" type="xsd:normalizedString" />
			<xsd:element name="year" type="xsd:nonNegativeInteger" />
			<!-- Whitespace should collapse -->
			<xsd:element name="title" type="xsd:token" />
			<!-- Whitespace should be preserved -->
			<xsd:element name="lyrics" type="xsd:string" />
			<!-- Whitespace should collapse -->
			<xsd:element name="length" type="xsd:duration" />
			<xsd:element name="album" type="CollapsedString" />
			<xsd:element name="location" type="Normalized" />
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== fingo/xactus/original_repo_content/xml/tests/org.eclipse.wst.xml.core.tests/src/org/eclipse/wst/xml/core/tests/format/testfiles/xml/xml-whitespace-xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<song xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="xml-whitespace.xsd">
	<artist>		 Some 	Singer
	</artist>
	<year>	1992 </year>
	<title>   	Lorem		    ipsum dolor	</title>
	<lyrics>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
		 Nunc in nisi. Integer quis quam non eros accumsan elementum.
			Sed risus orci,		 lobortis at, pulvinar at, varius ac, neque.
	Morbi pede nulla, tincidunt ac, semper vel, ultricies vitae, lacus.
		Nunc nunc.		   </lyrics>
	<length>2</length>
	<album>	   	Lorem 	ipsum dolor </album>
	<location>    	Raleigh, 	NC, 					USA		</location>
</song>
